package com.rca.entity;

// default package
// Generated Mar 10, 2015 7:18:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LoginDetails generated by hbm2java
 */
@Entity
@Table(name = "login_details", catalog = "rcautility")
public class LoginDetails implements java.io.Serializable {

	private String loginId;
	private String password;
	private String role;

	public LoginDetails() {
	}

	public LoginDetails(String loginId, String password) {
		this.loginId = loginId;
		this.password = password;
	}

	@Id
	@Column(name = "login_id", unique = true, nullable = false, length = 45)
	public String getLoginId() {
		return this.loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@Column(name = "role", nullable = true, length = 30)
	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

}
