package com.rca.entity;

// default package
// Generated Mar 10, 2015 7:18:09 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RcaCount generated by hbm2java
 */
@Entity
@Table(name = "rca_count", catalog = "rcautility")
public class RcaCount implements java.io.Serializable {

	private Integer rcaCountId;
	private ProjectDetails projectDetails;
	private Integer mrProductBacklog;
	private Integer mrQa;
	private Integer mrUat;
	private Integer mrProd;
	private Integer crProductBacklog;
	private Integer crQa;
	private Integer crUat;
	private Integer crProd;
	private Integer configProductBacklog;
	private Integer configQa;
	private Integer configUat;
	private Integer configProd;
	private Integer ccbProductBacklog;
	private Integer ccbQa;
	private Integer ccbUat;
	private Integer ccbProd;
	private Integer adProductBacklog;
	private Integer adQa;
	private Integer adUat;
	private Integer adProd;
	private Integer dupProductBacklog;
	private Integer dupQa;
	private Integer dupUat;
	private Integer dupProd;
	private Integer nadProductBacklog;
	private Integer nadQa;
	private Integer nadUat;
	private Integer nadProd;
	private Integer bsiProductBacklog;
	private Integer bsiQa;
	private Integer bsiUat;
	private Integer bsiProd;
	private Integer utrProductBacklog;
	private Integer utrQa;
	private Integer utrUat;
	private Integer utrProd;
	private Integer pdProductBacklog;
	private Integer pdQa;
	private Integer pdUat;
	private Integer pdProd;
	private Integer iiProductBacklog;
	private Integer iiQa;
	private Integer iiUat;
	private Integer iiProd;
	private Integer diProductBacklog;
	private Integer diQa;
	private Integer diUat;
	private Integer diProd;
	private Integer roQa;
	private Integer roUat;
	private Integer roProd;
	private String week;
	private Integer planProductBacklog;
	private Integer planQa;
	private Integer planUat;
	private Integer planProd;
	private Integer rateProductBacklog;
	private Integer rateQa;
	private Integer rateUat;
	private Integer rateProd;
	private Integer rpaProductBacklog;
	private Integer rpaQa;
	private Integer rpaUat;
	private Integer rpaProd;
	private Integer acProductBacklog;
	private Integer acQa;
	private Integer acUat;
	private Integer acProd;
	private Integer tiProductBacklog;
	private Integer tiQa;
	private Integer tiUat;
	private Integer tiProd;
	private Integer dpProductBacklog;
	private Integer dpQa;
	private Integer dpUat;
	private Integer dpProd;
	private Integer envProductBacklog;
	private Integer envQa;
	private Integer envUat;
	private Integer envProd;
	private Integer coProductBacklog;
	private Integer coQa;
	private Integer coUat;
	private Integer coProd;
	private Integer ffmProductBacklog;
	private Integer ffmQa;
	private Integer ffmUat;
	private Integer ffmProd;
	private Integer crmesbProductBacklog;
	private Integer crmesbQa;
	private Integer crmesbUat;
	private Integer crmesbProd;
	private Integer otpProductBacklog;
	private Integer otpQa;
	private Integer otpUat;
	private Integer otpProd;
	private Integer pmuuProductBacklog;
	private Integer pmuuQa;
	private Integer pmuuUat;
	private Integer pmuuProd;
	private Integer ioProductBacklog;
	private Integer ioQa;
	private Integer ioUat;
	private Integer ioProd;

	public RcaCount() {
	}

	public RcaCount(ProjectDetails projectDetails, Integer mrProductBacklog,
			Integer mrQa, Integer mrUat, Integer mrProd,
			Integer crProductBacklog, Integer crQa, Integer crUat,
			Integer crProd, Integer configProductBacklog, Integer configQa,
			Integer configUat, Integer configProd, Integer ccbProductBacklog,
			Integer ccbQa, Integer ccbUat, Integer ccbProd,
			Integer adProductBacklog, Integer adQa, Integer adUat,
			Integer adProd, Integer dupProductBacklog, Integer dupQa,
			Integer dupUat, Integer dupProd, Integer nadProductBacklog,
			Integer nadQa, Integer nadUat, Integer nadProd,
			Integer bsiProductBacklog, Integer bsiQa, Integer bsiUat,
			Integer bsiProd, Integer utrProductBacklog, Integer utrQa,
			Integer utrUat, Integer utrProd, Integer pdProductBacklog,
			Integer pdQa, Integer pdUat, Integer pdProd,
			Integer iiProductBacklog, Integer iiQa, Integer iiUat,
			Integer iiProd, Integer diProductBacklog, Integer diQa,
			Integer diUat, Integer diProd, Integer roQa, Integer roUat,
			Integer roProd, String week, Integer planProductBacklog,
			Integer planQa, Integer planUat, Integer planProd,
			Integer rateProductBacklog, Integer rateQa, Integer rateUat,
			Integer rateProd, Integer rpaProductBacklog, Integer rpaQa,
			Integer rpaUat, Integer rpaProd, Integer acProductBacklog,
			Integer acQa, Integer acUat, Integer acProd,
			Integer tiProductBacklog, Integer tiQa, Integer tiUat,
			Integer tiProd, Integer dpProductBacklog, Integer dpQa,
			Integer dpUat, Integer dpProd, Integer envProductBacklog,
			Integer envQa, Integer envUat, Integer envProd,
			Integer coProductBacklog, Integer coQa, Integer coUat,
			Integer coProd, Integer ffmProductBacklog, Integer ffmQa,
			Integer ffmUat, Integer ffmProd, Integer crmesbProductBacklog,
			Integer crmesbQa, Integer crmesbUat, Integer crmesbProd,
			Integer otpProductBacklog, Integer otpQa, Integer otpUat,
			Integer otpProd, Integer pmuuProductBacklog, Integer pmuuQa,
			Integer pmuuUat, Integer pmuuProd, Integer ioProductBacklog,
			Integer ioQa, Integer ioUat, Integer ioProd) {
		this.projectDetails = projectDetails;
		this.mrProductBacklog = mrProductBacklog;
		this.mrQa = mrQa;
		this.mrUat = mrUat;
		this.mrProd = mrProd;
		this.crProductBacklog = crProductBacklog;
		this.crQa = crQa;
		this.crUat = crUat;
		this.crProd = crProd;
		this.configProductBacklog = configProductBacklog;
		this.configQa = configQa;
		this.configUat = configUat;
		this.configProd = configProd;
		this.ccbProductBacklog = ccbProductBacklog;
		this.ccbQa = ccbQa;
		this.ccbUat = ccbUat;
		this.ccbProd = ccbProd;
		this.adProductBacklog = adProductBacklog;
		this.adQa = adQa;
		this.adUat = adUat;
		this.adProd = adProd;
		this.dupProductBacklog = dupProductBacklog;
		this.dupQa = dupQa;
		this.dupUat = dupUat;
		this.dupProd = dupProd;
		this.nadProductBacklog = nadProductBacklog;
		this.nadQa = nadQa;
		this.nadUat = nadUat;
		this.nadProd = nadProd;
		this.bsiProductBacklog = bsiProductBacklog;
		this.bsiQa = bsiQa;
		this.bsiUat = bsiUat;
		this.bsiProd = bsiProd;
		this.utrProductBacklog = utrProductBacklog;
		this.utrQa = utrQa;
		this.utrUat = utrUat;
		this.utrProd = utrProd;
		this.pdProductBacklog = pdProductBacklog;
		this.pdQa = pdQa;
		this.pdUat = pdUat;
		this.pdProd = pdProd;
		this.iiProductBacklog = iiProductBacklog;
		this.iiQa = iiQa;
		this.iiUat = iiUat;
		this.iiProd = iiProd;
		this.diProductBacklog = diProductBacklog;
		this.diQa = diQa;
		this.diUat = diUat;
		this.diProd = diProd;
		this.roQa = roQa;
		this.roUat = roUat;
		this.roProd = roProd;
		this.week = week;
		this.planProductBacklog = planProductBacklog;
		this.planQa = planQa;
		this.planUat = planUat;
		this.planProd = planProd;
		this.rateProductBacklog = rateProductBacklog;
		this.rateQa = rateQa;
		this.rateUat = rateUat;
		this.rateProd = rateProd;
		this.rpaProductBacklog = rpaProductBacklog;
		this.rpaQa = rpaQa;
		this.rpaUat = rpaUat;
		this.rpaProd = rpaProd;
		this.acProductBacklog = acProductBacklog;
		this.acQa = acQa;
		this.acUat = acUat;
		this.acProd = acProd;
		this.tiProductBacklog = tiProductBacklog;
		this.tiQa = tiQa;
		this.tiUat = tiUat;
		this.tiProd = tiProd;
		this.dpProductBacklog = dpProductBacklog;
		this.dpQa = dpQa;
		this.dpUat = dpUat;
		this.dpProd = dpProd;
		this.envProductBacklog = envProductBacklog;
		this.envQa = envQa;
		this.envUat = envUat;
		this.envProd = envProd;
		this.coProductBacklog = coProductBacklog;
		this.coQa = coQa;
		this.coUat = coUat;
		this.coProd = coProd;
		this.ffmProductBacklog = ffmProductBacklog;
		this.ffmQa = ffmQa;
		this.ffmUat = ffmUat;
		this.ffmProd = ffmProd;
		this.crmesbProductBacklog = crmesbProductBacklog;
		this.crmesbQa = crmesbQa;
		this.crmesbUat = crmesbUat;
		this.crmesbProd = crmesbProd;
		this.otpProductBacklog = otpProductBacklog;
		this.otpQa = otpQa;
		this.otpUat = otpUat;
		this.otpProd = otpProd;
		this.pmuuProductBacklog = pmuuProductBacklog;
		this.pmuuQa = pmuuQa;
		this.pmuuUat = pmuuUat;
		this.pmuuProd = pmuuProd;
		this.ioProductBacklog = ioProductBacklog;
		this.ioQa = ioQa;
		this.ioUat = ioUat;
		this.ioProd = ioProd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "rca_count_id", unique = true, nullable = false)
	public Integer getRcaCountId() {
		return this.rcaCountId;
	}

	public void setRcaCountId(Integer rcaCountId) {
		this.rcaCountId = rcaCountId;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade= CascadeType.ALL)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return this.projectDetails;
	}

	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@Column(name = "mr_product_backlog")
	public Integer getMrProductBacklog() {
		return this.mrProductBacklog;
	}

	public void setMrProductBacklog(Integer mrProductBacklog) {
		this.mrProductBacklog = mrProductBacklog;
	}

	@Column(name = "mr_qa")
	public Integer getMrQa() {
		return this.mrQa;
	}

	public void setMrQa(Integer mrQa) {
		this.mrQa = mrQa;
	}

	@Column(name = "mr_uat")
	public Integer getMrUat() {
		return this.mrUat;
	}

	public void setMrUat(Integer mrUat) {
		this.mrUat = mrUat;
	}

	@Column(name = "mr_prod")
	public Integer getMrProd() {
		return this.mrProd;
	}

	public void setMrProd(Integer mrProd) {
		this.mrProd = mrProd;
	}

	@Column(name = "cr_product_backlog")
	public Integer getCrProductBacklog() {
		return this.crProductBacklog;
	}

	public void setCrProductBacklog(Integer crProductBacklog) {
		this.crProductBacklog = crProductBacklog;
	}

	@Column(name = "cr_qa")
	public Integer getCrQa() {
		return this.crQa;
	}

	public void setCrQa(Integer crQa) {
		this.crQa = crQa;
	}

	@Column(name = "cr_uat")
	public Integer getCrUat() {
		return this.crUat;
	}

	public void setCrUat(Integer crUat) {
		this.crUat = crUat;
	}

	@Column(name = "cr_prod")
	public Integer getCrProd() {
		return this.crProd;
	}

	public void setCrProd(Integer crProd) {
		this.crProd = crProd;
	}

	@Column(name = "config_product_backlog")
	public Integer getConfigProductBacklog() {
		return this.configProductBacklog;
	}

	public void setConfigProductBacklog(Integer configProductBacklog) {
		this.configProductBacklog = configProductBacklog;
	}

	@Column(name = "config_qa")
	public Integer getConfigQa() {
		return this.configQa;
	}

	public void setConfigQa(Integer configQa) {
		this.configQa = configQa;
	}

	@Column(name = "config_uat")
	public Integer getConfigUat() {
		return this.configUat;
	}

	public void setConfigUat(Integer configUat) {
		this.configUat = configUat;
	}

	@Column(name = "config_prod")
	public Integer getConfigProd() {
		return this.configProd;
	}

	public void setConfigProd(Integer configProd) {
		this.configProd = configProd;
	}

	@Column(name = "ccb_product_backlog")
	public Integer getCcbProductBacklog() {
		return this.ccbProductBacklog;
	}

	public void setCcbProductBacklog(Integer ccbProductBacklog) {
		this.ccbProductBacklog = ccbProductBacklog;
	}

	@Column(name = "ccb_qa")
	public Integer getCcbQa() {
		return this.ccbQa;
	}

	public void setCcbQa(Integer ccbQa) {
		this.ccbQa = ccbQa;
	}

	@Column(name = "ccb_uat")
	public Integer getCcbUat() {
		return this.ccbUat;
	}

	public void setCcbUat(Integer ccbUat) {
		this.ccbUat = ccbUat;
	}

	@Column(name = "ccb_prod")
	public Integer getCcbProd() {
		return this.ccbProd;
	}

	public void setCcbProd(Integer ccbProd) {
		this.ccbProd = ccbProd;
	}

	@Column(name = "ad_product_backlog")
	public Integer getAdProductBacklog() {
		return this.adProductBacklog;
	}

	public void setAdProductBacklog(Integer adProductBacklog) {
		this.adProductBacklog = adProductBacklog;
	}

	@Column(name = "ad_qa")
	public Integer getAdQa() {
		return this.adQa;
	}

	public void setAdQa(Integer adQa) {
		this.adQa = adQa;
	}

	@Column(name = "ad_uat")
	public Integer getAdUat() {
		return this.adUat;
	}

	public void setAdUat(Integer adUat) {
		this.adUat = adUat;
	}

	@Column(name = "ad_prod")
	public Integer getAdProd() {
		return this.adProd;
	}

	public void setAdProd(Integer adProd) {
		this.adProd = adProd;
	}

	@Column(name = "dup_product_backlog")
	public Integer getDupProductBacklog() {
		return this.dupProductBacklog;
	}

	public void setDupProductBacklog(Integer dupProductBacklog) {
		this.dupProductBacklog = dupProductBacklog;
	}

	@Column(name = "dup_qa")
	public Integer getDupQa() {
		return this.dupQa;
	}

	public void setDupQa(Integer dupQa) {
		this.dupQa = dupQa;
	}

	@Column(name = "dup_uat")
	public Integer getDupUat() {
		return this.dupUat;
	}

	public void setDupUat(Integer dupUat) {
		this.dupUat = dupUat;
	}

	@Column(name = "dup_prod")
	public Integer getDupProd() {
		return this.dupProd;
	}

	public void setDupProd(Integer dupProd) {
		this.dupProd = dupProd;
	}

	@Column(name = "nad_product_backlog")
	public Integer getNadProductBacklog() {
		return this.nadProductBacklog;
	}

	public void setNadProductBacklog(Integer nadProductBacklog) {
		this.nadProductBacklog = nadProductBacklog;
	}

	@Column(name = "nad_qa")
	public Integer getNadQa() {
		return this.nadQa;
	}

	public void setNadQa(Integer nadQa) {
		this.nadQa = nadQa;
	}

	@Column(name = "nad_uat")
	public Integer getNadUat() {
		return this.nadUat;
	}

	public void setNadUat(Integer nadUat) {
		this.nadUat = nadUat;
	}

	@Column(name = "nad_prod")
	public Integer getNadProd() {
		return this.nadProd;
	}

	public void setNadProd(Integer nadProd) {
		this.nadProd = nadProd;
	}

	@Column(name = "bsi_product_backlog")
	public Integer getBsiProductBacklog() {
		return this.bsiProductBacklog;
	}

	public void setBsiProductBacklog(Integer bsiProductBacklog) {
		this.bsiProductBacklog = bsiProductBacklog;
	}

	@Column(name = "bsi_qa")
	public Integer getBsiQa() {
		return this.bsiQa;
	}

	public void setBsiQa(Integer bsiQa) {
		this.bsiQa = bsiQa;
	}

	@Column(name = "bsi_uat")
	public Integer getBsiUat() {
		return this.bsiUat;
	}

	public void setBsiUat(Integer bsiUat) {
		this.bsiUat = bsiUat;
	}

	@Column(name = "bsi_prod")
	public Integer getBsiProd() {
		return this.bsiProd;
	}

	public void setBsiProd(Integer bsiProd) {
		this.bsiProd = bsiProd;
	}

	@Column(name = "utr_product_backlog")
	public Integer getUtrProductBacklog() {
		return this.utrProductBacklog;
	}

	public void setUtrProductBacklog(Integer utrProductBacklog) {
		this.utrProductBacklog = utrProductBacklog;
	}

	@Column(name = "utr_qa")
	public Integer getUtrQa() {
		return this.utrQa;
	}

	public void setUtrQa(Integer utrQa) {
		this.utrQa = utrQa;
	}

	@Column(name = "utr_uat")
	public Integer getUtrUat() {
		return this.utrUat;
	}

	public void setUtrUat(Integer utrUat) {
		this.utrUat = utrUat;
	}

	@Column(name = "utr_prod")
	public Integer getUtrProd() {
		return this.utrProd;
	}

	public void setUtrProd(Integer utrProd) {
		this.utrProd = utrProd;
	}

	@Column(name = "pd_product_backlog")
	public Integer getPdProductBacklog() {
		return this.pdProductBacklog;
	}

	public void setPdProductBacklog(Integer pdProductBacklog) {
		this.pdProductBacklog = pdProductBacklog;
	}

	@Column(name = "pd_qa")
	public Integer getPdQa() {
		return this.pdQa;
	}

	public void setPdQa(Integer pdQa) {
		this.pdQa = pdQa;
	}

	@Column(name = "pd_uat")
	public Integer getPdUat() {
		return this.pdUat;
	}

	public void setPdUat(Integer pdUat) {
		this.pdUat = pdUat;
	}

	@Column(name = "pd_prod")
	public Integer getPdProd() {
		return this.pdProd;
	}

	public void setPdProd(Integer pdProd) {
		this.pdProd = pdProd;
	}

	@Column(name = "ii_product_backlog")
	public Integer getIiProductBacklog() {
		return this.iiProductBacklog;
	}

	public void setIiProductBacklog(Integer iiProductBacklog) {
		this.iiProductBacklog = iiProductBacklog;
	}

	@Column(name = "ii_qa")
	public Integer getIiQa() {
		return this.iiQa;
	}

	public void setIiQa(Integer iiQa) {
		this.iiQa = iiQa;
	}

	@Column(name = "ii_uat")
	public Integer getIiUat() {
		return this.iiUat;
	}

	public void setIiUat(Integer iiUat) {
		this.iiUat = iiUat;
	}

	@Column(name = "ii_prod")
	public Integer getIiProd() {
		return this.iiProd;
	}

	public void setIiProd(Integer iiProd) {
		this.iiProd = iiProd;
	}

	@Column(name = "di_product_backlog")
	public Integer getDiProductBacklog() {
		return this.diProductBacklog;
	}

	public void setDiProductBacklog(Integer diProductBacklog) {
		this.diProductBacklog = diProductBacklog;
	}

	@Column(name = "di_qa")
	public Integer getDiQa() {
		return this.diQa;
	}

	public void setDiQa(Integer diQa) {
		this.diQa = diQa;
	}

	@Column(name = "di_uat")
	public Integer getDiUat() {
		return this.diUat;
	}

	public void setDiUat(Integer diUat) {
		this.diUat = diUat;
	}

	@Column(name = "di_prod")
	public Integer getDiProd() {
		return this.diProd;
	}

	public void setDiProd(Integer diProd) {
		this.diProd = diProd;
	}

	@Column(name = "ro_qa")
	public Integer getRoQa() {
		return this.roQa;
	}

	public void setRoQa(Integer roQa) {
		this.roQa = roQa;
	}

	@Column(name = "ro_uat")
	public Integer getRoUat() {
		return this.roUat;
	}

	public void setRoUat(Integer roUat) {
		this.roUat = roUat;
	}

	@Column(name = "ro_prod")
	public Integer getRoProd() {
		return this.roProd;
	}

	public void setRoProd(Integer roProd) {
		this.roProd = roProd;
	}

	@Column(name = "week", length = 50)
	public String getWeek() {
		return this.week;
	}

	public void setWeek(String week) {
		this.week = week;
	}

	@Column(name = "plan_product_backlog")
	public Integer getPlanProductBacklog() {
		return this.planProductBacklog;
	}

	public void setPlanProductBacklog(Integer planProductBacklog) {
		this.planProductBacklog = planProductBacklog;
	}

	@Column(name = "plan_qa")
	public Integer getPlanQa() {
		return this.planQa;
	}

	public void setPlanQa(Integer planQa) {
		this.planQa = planQa;
	}

	@Column(name = "plan_uat")
	public Integer getPlanUat() {
		return this.planUat;
	}

	public void setPlanUat(Integer planUat) {
		this.planUat = planUat;
	}

	@Column(name = "plan_prod")
	public Integer getPlanProd() {
		return this.planProd;
	}

	public void setPlanProd(Integer planProd) {
		this.planProd = planProd;
	}

	@Column(name = "rate_product_backlog")
	public Integer getRateProductBacklog() {
		return this.rateProductBacklog;
	}

	public void setRateProductBacklog(Integer rateProductBacklog) {
		this.rateProductBacklog = rateProductBacklog;
	}

	@Column(name = "rate_qa")
	public Integer getRateQa() {
		return this.rateQa;
	}

	public void setRateQa(Integer rateQa) {
		this.rateQa = rateQa;
	}

	@Column(name = "rate_uat")
	public Integer getRateUat() {
		return this.rateUat;
	}

	public void setRateUat(Integer rateUat) {
		this.rateUat = rateUat;
	}

	@Column(name = "rate_prod")
	public Integer getRateProd() {
		return this.rateProd;
	}

	public void setRateProd(Integer rateProd) {
		this.rateProd = rateProd;
	}

	@Column(name = "rpa_product_backlog")
	public Integer getRpaProductBacklog() {
		return this.rpaProductBacklog;
	}

	public void setRpaProductBacklog(Integer rpaProductBacklog) {
		this.rpaProductBacklog = rpaProductBacklog;
	}

	@Column(name = "rpa_qa")
	public Integer getRpaQa() {
		return this.rpaQa;
	}

	public void setRpaQa(Integer rpaQa) {
		this.rpaQa = rpaQa;
	}

	@Column(name = "rpa_uat")
	public Integer getRpaUat() {
		return this.rpaUat;
	}

	public void setRpaUat(Integer rpaUat) {
		this.rpaUat = rpaUat;
	}

	@Column(name = "rpa_prod")
	public Integer getRpaProd() {
		return this.rpaProd;
	}

	public void setRpaProd(Integer rpaProd) {
		this.rpaProd = rpaProd;
	}

	@Column(name = "ac_product_backlog")
	public Integer getAcProductBacklog() {
		return this.acProductBacklog;
	}

	public void setAcProductBacklog(Integer acProductBacklog) {
		this.acProductBacklog = acProductBacklog;
	}

	@Column(name = "ac_qa")
	public Integer getAcQa() {
		return this.acQa;
	}

	public void setAcQa(Integer acQa) {
		this.acQa = acQa;
	}

	@Column(name = "ac_uat")
	public Integer getAcUat() {
		return this.acUat;
	}

	public void setAcUat(Integer acUat) {
		this.acUat = acUat;
	}

	@Column(name = "ac_prod")
	public Integer getAcProd() {
		return this.acProd;
	}

	public void setAcProd(Integer acProd) {
		this.acProd = acProd;
	}

	@Column(name = "ti_product_backlog")
	public Integer getTiProductBacklog() {
		return this.tiProductBacklog;
	}

	public void setTiProductBacklog(Integer tiProductBacklog) {
		this.tiProductBacklog = tiProductBacklog;
	}

	@Column(name = "ti_qa")
	public Integer getTiQa() {
		return this.tiQa;
	}

	public void setTiQa(Integer tiQa) {
		this.tiQa = tiQa;
	}

	@Column(name = "ti_uat")
	public Integer getTiUat() {
		return this.tiUat;
	}

	public void setTiUat(Integer tiUat) {
		this.tiUat = tiUat;
	}

	@Column(name = "ti_prod")
	public Integer getTiProd() {
		return this.tiProd;
	}

	public void setTiProd(Integer tiProd) {
		this.tiProd = tiProd;
	}

	@Column(name = "dp_product_backlog")
	public Integer getDpProductBacklog() {
		return this.dpProductBacklog;
	}

	public void setDpProductBacklog(Integer dpProductBacklog) {
		this.dpProductBacklog = dpProductBacklog;
	}

	@Column(name = "dp_qa")
	public Integer getDpQa() {
		return this.dpQa;
	}

	public void setDpQa(Integer dpQa) {
		this.dpQa = dpQa;
	}

	@Column(name = "dp_uat")
	public Integer getDpUat() {
		return this.dpUat;
	}

	public void setDpUat(Integer dpUat) {
		this.dpUat = dpUat;
	}

	@Column(name = "dp_prod")
	public Integer getDpProd() {
		return this.dpProd;
	}

	public void setDpProd(Integer dpProd) {
		this.dpProd = dpProd;
	}

	@Column(name = "env_product_backlog")
	public Integer getEnvProductBacklog() {
		return this.envProductBacklog;
	}

	public void setEnvProductBacklog(Integer envProductBacklog) {
		this.envProductBacklog = envProductBacklog;
	}

	@Column(name = "env_qa")
	public Integer getEnvQa() {
		return this.envQa;
	}

	public void setEnvQa(Integer envQa) {
		this.envQa = envQa;
	}

	@Column(name = "env_uat")
	public Integer getEnvUat() {
		return this.envUat;
	}

	public void setEnvUat(Integer envUat) {
		this.envUat = envUat;
	}

	@Column(name = "env_prod")
	public Integer getEnvProd() {
		return this.envProd;
	}

	public void setEnvProd(Integer envProd) {
		this.envProd = envProd;
	}

	@Column(name = "co_product_backlog")
	public Integer getCoProductBacklog() {
		return this.coProductBacklog;
	}

	public void setCoProductBacklog(Integer coProductBacklog) {
		this.coProductBacklog = coProductBacklog;
	}

	@Column(name = "co_qa")
	public Integer getCoQa() {
		return this.coQa;
	}

	public void setCoQa(Integer coQa) {
		this.coQa = coQa;
	}

	@Column(name = "co_uat")
	public Integer getCoUat() {
		return this.coUat;
	}

	public void setCoUat(Integer coUat) {
		this.coUat = coUat;
	}

	@Column(name = "co_prod")
	public Integer getCoProd() {
		return this.coProd;
	}

	public void setCoProd(Integer coProd) {
		this.coProd = coProd;
	}

	@Column(name = "ffm_product_backlog")
	public Integer getFfmProductBacklog() {
		return this.ffmProductBacklog;
	}

	public void setFfmProductBacklog(Integer ffmProductBacklog) {
		this.ffmProductBacklog = ffmProductBacklog;
	}

	@Column(name = "ffm_qa")
	public Integer getFfmQa() {
		return this.ffmQa;
	}

	public void setFfmQa(Integer ffmQa) {
		this.ffmQa = ffmQa;
	}

	@Column(name = "ffm_uat")
	public Integer getFfmUat() {
		return this.ffmUat;
	}

	public void setFfmUat(Integer ffmUat) {
		this.ffmUat = ffmUat;
	}

	@Column(name = "ffm_prod")
	public Integer getFfmProd() {
		return this.ffmProd;
	}

	public void setFfmProd(Integer ffmProd) {
		this.ffmProd = ffmProd;
	}

	@Column(name = "crmesb_product_backlog")
	public Integer getCrmesbProductBacklog() {
		return this.crmesbProductBacklog;
	}

	public void setCrmesbProductBacklog(Integer crmesbProductBacklog) {
		this.crmesbProductBacklog = crmesbProductBacklog;
	}

	@Column(name = "crmesb_qa")
	public Integer getCrmesbQa() {
		return this.crmesbQa;
	}

	public void setCrmesbQa(Integer crmesbQa) {
		this.crmesbQa = crmesbQa;
	}

	@Column(name = "crmesb_uat")
	public Integer getCrmesbUat() {
		return this.crmesbUat;
	}

	public void setCrmesbUat(Integer crmesbUat) {
		this.crmesbUat = crmesbUat;
	}

	@Column(name = "crmesb_prod")
	public Integer getCrmesbProd() {
		return this.crmesbProd;
	}

	public void setCrmesbProd(Integer crmesbProd) {
		this.crmesbProd = crmesbProd;
	}

	@Column(name = "otp_product_backlog")
	public Integer getOtpProductBacklog() {
		return this.otpProductBacklog;
	}

	public void setOtpProductBacklog(Integer otpProductBacklog) {
		this.otpProductBacklog = otpProductBacklog;
	}

	@Column(name = "otp_qa")
	public Integer getOtpQa() {
		return this.otpQa;
	}

	public void setOtpQa(Integer otpQa) {
		this.otpQa = otpQa;
	}

	@Column(name = "otp_uat")
	public Integer getOtpUat() {
		return this.otpUat;
	}

	public void setOtpUat(Integer otpUat) {
		this.otpUat = otpUat;
	}

	@Column(name = "otp_prod")
	public Integer getOtpProd() {
		return this.otpProd;
	}

	public void setOtpProd(Integer otpProd) {
		this.otpProd = otpProd;
	}

	@Column(name = "pmuu_product_backlog")
	public Integer getPmuuProductBacklog() {
		return this.pmuuProductBacklog;
	}

	public void setPmuuProductBacklog(Integer pmuuProductBacklog) {
		this.pmuuProductBacklog = pmuuProductBacklog;
	}

	@Column(name = "pmuu_qa")
	public Integer getPmuuQa() {
		return this.pmuuQa;
	}

	public void setPmuuQa(Integer pmuuQa) {
		this.pmuuQa = pmuuQa;
	}

	@Column(name = "pmuu_uat")
	public Integer getPmuuUat() {
		return this.pmuuUat;
	}

	public void setPmuuUat(Integer pmuuUat) {
		this.pmuuUat = pmuuUat;
	}

	@Column(name = "pmuu_prod")
	public Integer getPmuuProd() {
		return this.pmuuProd;
	}

	public void setPmuuProd(Integer pmuuProd) {
		this.pmuuProd = pmuuProd;
	}

	@Column(name = "io_product_backlog")
	public Integer getIoProductBacklog() {
		return this.ioProductBacklog;
	}

	public void setIoProductBacklog(Integer ioProductBacklog) {
		this.ioProductBacklog = ioProductBacklog;
	}

	@Column(name = "io_qa")
	public Integer getIoQa() {
		return this.ioQa;
	}

	public void setIoQa(Integer ioQa) {
		this.ioQa = ioQa;
	}

	@Column(name = "io_uat")
	public Integer getIoUat() {
		return this.ioUat;
	}

	public void setIoUat(Integer ioUat) {
		this.ioUat = ioUat;
	}

	@Column(name = "io_prod")
	public Integer getIoProd() {
		return this.ioProd;
	}

	public void setIoProd(Integer ioProd) {
		this.ioProd = ioProd;
	}

}
