package com.rca.entity;

//default package
//Generated Apr 02, 2015 4:02:09 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.opensymphony.xwork2.conversion.annotations.Conversion;
import com.opensymphony.xwork2.conversion.annotations.TypeConversion;

/**
* ProjectSprintDetails generated by hbm2java
*/

@Entity
@Table(name = "sprint_report", catalog = "rcautility")
public class SprintReport implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer sprintReportId;
	private ProjectDetails projectDetails;
	private String sprintName;
	private Integer spCommitted;
	private Integer spDelivered;
	private Integer spAddedInMid;
	private Integer teamCapacity;
	private Date startDate;
	private Date endDate;
	private Integer devMembers;
	private Integer qaMembers;
	private String isKanbanFollowed;
  public SprintReport(){
		
	}
	
	public SprintReport(Integer sprintReportId, ProjectDetails projectDetails,
			String sprintName, Integer spCommitted,
			Integer spDelivered, Integer spAddedInMid,
			Integer teamCapacity,Integer devMembers, Integer qaMembers,Date startDate,Date endDate) {
		this.sprintReportId = sprintReportId;
		this.projectDetails = projectDetails;
		this.sprintName = sprintName;
		this.spCommitted = spCommitted;
		this.spDelivered = spDelivered;
		this.spAddedInMid = spAddedInMid;
		this.teamCapacity = teamCapacity;
		this.startDate = startDate;
		this.endDate = endDate;
		this.devMembers = qaMembers;
		this.qaMembers = qaMembers;
		this.isKanbanFollowed=isKanbanFollowed;
	}
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sprint_report_id", unique = true, nullable = false)
	public Integer getSprintReportId() {
		return sprintReportId;
	}

	public void setSprintReportId(Integer sprintReportId) {
		this.sprintReportId = sprintReportId;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade= CascadeType.REMOVE)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return projectDetails;
	}


	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}
	@Column(name = "sprint_name",unique=true)
	public String getSprintName() {
		return sprintName;
	}

	public void setSprintName(String sprintName) {
		this.sprintName = sprintName;
	}
	@Column(name = "sprint_user_story_committed")
	public Integer getSpCommitted() {
		return spCommitted;
	}

	public void setSpCommitted(Integer spCommitted) {
		this.spCommitted = spCommitted;
	}
	@Column(name = "sprint_user_story_delivered")
	public Integer getSpDelivered() {
		return spDelivered;
	}

	public void setSpDelivered(Integer spDelivered) {
		this.spDelivered = spDelivered;
	}
	@Column(name = "sprint_user_story_added_in_mid")
	public Integer getSpAddedInMid() {
		return spAddedInMid;
	}

	public void setSpAddedInMid(Integer spAddedInMid) {
		this.spAddedInMid = spAddedInMid;
	}
	@Column(name = "sprint_team_capacity")
	public Integer getTeamCapacity() {
		return teamCapacity;
	}

	public void setTeamCapacity(Integer teamCapacity) {
		this.teamCapacity = teamCapacity;
	}
	@Column(name = "sprint_start_date")
	public Date getStartDate() {
		return startDate;
	}

	@Override
	public String toString() {
		return "SprintReport [sprintReportId=" + sprintReportId + ", projectDetails=" + projectDetails + ", sprintName="
				+ sprintName + ", spCommitted=" + spCommitted + ", spDelivered=" + spDelivered + ", spAddedInMid="
				+ spAddedInMid + ", teamCapacity=" + teamCapacity + ", startDate=" + startDate + ", endDate=" + endDate
				+ ", devMembers=" + devMembers + ", qaMembers=" + qaMembers + ", isKanbanFollowed=" + isKanbanFollowed
				+ "]";
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	
	@Column(name = "sprint_end_date")
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
		
	@Column(name = "dev_members")
	public Integer getDevMembers() {
		return devMembers;
	}


	public void setDevMembers(Integer devMembers) {
		this.devMembers = devMembers;
	}

	@Column(name = "qa_members")
	public Integer getQaMembers() {
		return qaMembers;
	}


	public void setQaMembers(Integer qaMembers) {
		this.qaMembers = qaMembers;
	}
	@Column(name = "IsKanbanFollowed")
	public String getIsKanbanFollowed() {
	    return isKanbanFollowed;
	 }

	public void setIsKanbanFollowed(String isKanbanFollowed) {
	    this.isKanbanFollowed = isKanbanFollowed;
	 }
	

}
