package com.rca.entity;

//default package
//Generated Apr 02, 2015 4:02:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
* ProjectSprintDetails generated by hbm2java
*/

@Entity
@Table(name = "sprint_report", catalog = "rcautility")
public class SprintReport implements java.io.Serializable {
	
	private Integer sprintReportId;
	private ProjectDetails projectDetails;
	private String week;
	private String sprint1Name;
	private Integer sprint1UserStory;
	private Integer sprint1BugCount;
	private String sprint2Name;
	private Integer sprint2UserStory;
	private Integer sprint2BugCount;
	private Integer devMembers;
	private Integer qaMembers;
	
	public SprintReport(){
		
	}
	
	public SprintReport(Integer sprintReportId, ProjectDetails projectDetails,
			String week, String sprint1Name, Integer sprint1UserStory,
			Integer sprint1BugCount, String sprint2Name,
			Integer sprint2UserStory, Integer sprint2BugCount,
			Integer devMembers, Integer qaMembers) {
		this.sprintReportId = sprintReportId;
		this.projectDetails = projectDetails;
		this.week = week;
		this.sprint1Name = sprint1Name;
		this.sprint1UserStory = sprint1UserStory;
		this.sprint1BugCount = sprint1BugCount;
		this.sprint2Name = sprint2Name;
		this.sprint2UserStory = sprint2UserStory;
		this.sprint2BugCount = sprint2BugCount;
		this.devMembers = devMembers;
		this.qaMembers = qaMembers;
	}
	
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sprint_report_id", unique = true, nullable = false)
	public Integer getSprintReportId() {
		return sprintReportId;
	}

	public void setSprintReportId(Integer sprintReportId) {
		this.sprintReportId = sprintReportId;
	}

	@ManyToOne(fetch = FetchType.EAGER, cascade= CascadeType.REMOVE)
	@JoinColumn(name = "project_id")
	public ProjectDetails getProjectDetails() {
		return projectDetails;
	}


	public void setProjectDetails(ProjectDetails projectDetails) {
		this.projectDetails = projectDetails;
	}

	@Column(name = "week", length = 50)
	public String getWeek() {
		return week;
	}


	public void setWeek(String week) {
		this.week = week;
	}

	@Column(name = "sprint1_name")
	public String getSprint1Name() {
		return sprint1Name;
	}


	public void setSprint1Name(String sprint1Name) {
		this.sprint1Name = sprint1Name;
	}

	@Column(name = "sprint1_user_story")
	public Integer getSprint1UserStory() {
		return sprint1UserStory;
	}


	public void setSprint1UserStory(Integer sprint1UserStory) {
		this.sprint1UserStory = sprint1UserStory;
	}

	@Column(name = "sprint1_bug_count")
	public Integer getSprint1BugCount() {
		return sprint1BugCount;
	}


	public void setSprint1BugCount(Integer sprint1BugCount) {
		this.sprint1BugCount = sprint1BugCount;
	}

	@Column(name = "sprint2_name")
	public String getSprint2Name() {
		return sprint2Name;
	}


	public void setSprint2Name(String sprint2Name) {
		this.sprint2Name = sprint2Name;
	}

	@Column(name = "sprint2_user_story")
	public Integer getSprint2UserStory() {
		return sprint2UserStory;
	}


	public void setSprint2UserStory(Integer sprint2UserStory) {
		this.sprint2UserStory = sprint2UserStory;
	}

	@Column(name = "sprint2_bug_count")
	public Integer getSprint2BugCount() {
		return sprint2BugCount;
	}


	public void setSprint2BugCount(Integer sprint2BugCount) {
		this.sprint2BugCount = sprint2BugCount;
	}

	@Column(name = "dev_members")
	public Integer getDevMembers() {
		return devMembers;
	}


	public void setDevMembers(Integer devMembers) {
		this.devMembers = devMembers;
	}

	@Column(name = "qa_members")
	public Integer getQaMembers() {
		return qaMembers;
	}


	public void setQaMembers(Integer qaMembers) {
		this.qaMembers = qaMembers;
	}

	
	
	
	
	
	

}
